### ISSUE TITLE
Make documentation link clearer

### ISSUE THREAD

**Issue by evetion** [glotzerlab/coxeter#152]
Small request to make the [documentation link](http://coxeter.readthedocs.io/en/latest/?badge=latest) clearer. Only the building badge in the `README.md` points to it, could be better described and added in the about section (website).

**Comment by bdice** [comment]
I added some basic information to the GitHub about section. @vyasr Please feel free to edit.
![image](https://user-images.githubusercontent.com/3943761/123560649-3b381080-d769-11eb-8a37-4e5d56753114.png)

Perhaps the "table of contents" section could be edited so that the link labeled "Documentation" is first and points to the ReadTheDocs website instead of linking to instructions later in the README about how to build the documentation locally.

**Comment by vyasr** [comment]
Thanks for making this change @bdice, it looks good to me! I like your suggestion, unfortunately I'm not aware of any way to do that with the rst contents. I've made some further improvements in #155 that hopefully help address the problem though, including adding an extended description of the package that also includes a link to the docs and retitling the "Documentation" section of the README to "Building Documentation" to avoid any confusion. Hopefully that is sufficient to address everyon'es concerns?
