### ISSUE TITLE
Issue with distance_to_surface documentation.

### ISSUE THREAD

**Issue by ispivack** [glotzerlab/coxeter#161]
### Description

In the documentation, distance_to_surface is listed as being a part of the ConvexPolyhedron class. However, it is not implemented in this class, and trying to call it on a convex polyhedron actually just calls the implementation in the base class (which just raises an error that it is not implemented). It seems like the function is not implemented in 3D at all, although I only spent time trying to get it to work on ConvexPolyhedron. The documentation mentions that the argument should be the phi/theta angles in 3D, which implies that it is implemented.

### To reproduce

shape = coxeter.shapes.ConvexPolyhedron([[1,0,0],[0,1,0],[0,0,1],[1,1,1]])
shape.distance_to_surface((0,np.pi/2))

### Error output

If possible, copy any terminal outputs or attach screenshots that provide additional information on the problem.

NotImplementedError: The distance to surface calculation is not implemented for this shape.

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Windows 10
 - Version of Python [e.g. 3.7]:  3.7.6
 - Version of coxeter [e.g. 1.0]: 0.6.1

**Comment by vyasr** [comment]
Just to close a loop from a discussion that we had offline, `distance_to_surface` is indeed not implemented in 3D. Since it is well defined in 3D and there was interested in developing the feature we defined the method as raising a `NotImplementedError` in the base class so that would be the default for any subclass that did not provide a suitable override. I don't think there's any bug here, it's simply an indication that a property that we _could_ support computing is not actually supported yet. If someone has interest in adding support for it I'd be happy to review, but until then I don't think there's any action to be taken here.
